config/routes.rb
LunchMail::Application.routes.draw do
  resources :groups do
    get :notice_all
    resources :users do
      member do
        get :notice
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :kicks, :only => %w() do
    member do
      get 'execute'
    end
  end

  root :to => "groups#show"

end

app/models/group.rb
# -*- coding: utf-8 -*-
class Group < ActiveRecord::Base
  has_many :users
  has_one :setting
  accepts_nested_attributes_for :setting

  WDAYS = ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"].freeze

  def self.send_notifications
    self.select_target_groups.each do |group|
      response_geo = ApiAccess.geo_api_get({:q => group.setting.area})
      until response_geo.result.error != "003"
        response_geo = ApiAccess.geo_api_get({:q => group.setting.area})
      end
      if response_geo.result.error == "001"
        np_users = group.active_users
        np_users.each do |user|
          Notifier.error_email(user, response_geo.result.error)
          Notifier.deliver_error_email(user, response_geo.result.error)
          Rails.logger.info "[Mail] send email to #{user.email}"
        end
      else
        response_rests = ApiAccess.get_response_by_group(group, response_geo.result.coordinate)

        day = Time.now
        response_rests.delete_if{ |rest| rest.holiday == WDAYS[day.wday] }

        response_rests.delete_if{ |rest| rest.opentime == nil }
        rests = response_rests.select{ |rest| rest.opentime.include?("11:00") || rest.opentime.include?("11:25") || rest.opentime.include?("11:30") || rest.opentime.include?("12:00")}

        if rests.empty?
          shop = "empty"
          np_users = group.active_users
          np_users.each do |user|
            Notifier.notice_email(user,shop)
            Notifier.deliver_notice_email(user,shop)
            Rails.logger.info "[Mail] send email to #{user.email}"
          end
        else
          np_user_groups = group.divide_groups
          np_user_groups.each do |np_user_group|
            shop = rests.instance_of?(Array) ? rests[rand(rests.size)] : rests
            members = np_user_group.map{ |member| member.name }.join(",")
            np_user_group.each do |user|
              begin
                Notifier.notice_email(user,shop,members)
                Notifier.deliver_notice_email(user,shop,members)
                Rails.logger.info "[Mail] send email to #{user.email}, shop:#{shop.name}, member:#{members}"
              rescue => e
                Rails.logger.error "Error: #{e}"
              end
            end
          end
        end
      end
    end
  end

  def self.select_target_groups
    self.select{|group| group.target_time? }
  end

  def target_time?
    current_time = Time.local(2011,1,1,Time.now.hour,Time.now.min,Time.now.sec)
    self.setting.notice_at >= current_time-7.second && self.setting.notice_at < current_time+8.second ? true : false
  end

  def active_users
    self.users.select{|user| user.active == true }
  end

  def divide_groups
    notice_users = self.active_users.sort_by{ rand }
    notice_users_count = notice_users.size
    groups = []

    if notice_users_count <= 5
      groups << notice_users
    elsif notice_users_count == 8
      notice_users.each_slice(4){ |four_users_group| groups << four_users_group }
    else
      cut_point = (( notice_users_count / 4 - 3 ) + notice_users_count % 4) * 4
      last_point = notice_users_count - 1
      three_groups = notice_users.slice!(cut_point..last_point)
      notice_users.each_slice(4){ |four_users_group| groups << four_users_group }
      three_groups.each_slice(3){ |three_users_group| groups << three_users_group }
      groups
    end
  end
end

app/controllers/groups_controller.rb
# -*- coding: utf-8 -*-
class GroupsController < ApplicationController
  skip_before_filter :load_group, :only => ["new", "create"]

  def new
    @group = Group.new
    @setting = @group.build_setting
  end

  def show
    redirect_to new_group_path unless @group
  end

  def edit
    @setting = @group.setting
  end

  def create
    params[:group][:setting_attributes]["notice_at(1i)"] = "2011"
    params[:group][:setting_attributes]["notice_at(2i)"] = "1"
    params[:group][:setting_attributes]["notice_at(3i)"] = "1"
    @group = Group.new(params[:group])
    if @group.save
      current_user.group = @group
      current_user.save
      redirect_to group_path(@group), :notice => "登録が完了しました。"
    else
      render :action => "new"
    end
  end

  def update
    if @group.update_attributes(params[:group])
      redirect_to group_path(@group), :notice => "登録情報を更新しました。"
    else
      render :action => "edit"
    end
  end

  def notice_all
    @group.users.each do |user|
      user.active = params[:status]
      user.save
    end
    respond_to do |format|
      format.js { render "notice_all" }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if @group.errors.any?
    #error_explanation
      %h2= "#{pluralize(@group.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg
  .alert-message.block-message.info
    = "設定した住所から半径300m圏内にある店舗がランダムで通知されます。"
  .clearfix
    = f.label "ランチグループ名"
    .input
      = f.text_field :name
  = f.fields_for :setting do |setting|
    .clearfix
      = setting.label "住所"
      .input
        = setting.text_field :area
    .clearfix
      = setting.label "通知時刻"
      .input
        - if Rails.env == 'production'
          = setting.datetime_select :notice_at, :discard_year => true, :discard_month => true, :discard_day => true, :minute_step => 10
        - else
          = setting.datetime_select :notice_at, :discard_year => true, :discard_month => true, :discard_day => true
    .actions
      = f.submit :class => "btn primary"

app/views/groups/edit.html.haml
.page-header
  %h1 登録情報の編集

%p= link_to "<< ホームへ戻る", group_path(@group)

= render :partial => "form"

app/views/groups/new.html.haml
.page-header
  %h1 新規登録

= render :partial => "form"

app/views/groups/show.html.haml
.page-header
  %h1 登録情報

%table.bordered-table.zebra-striped
  %tr
    %th.index_width
      項目
    %th
      内容

  %tr
    %td
      ランチグループ名
    %td
      = @group.name
  %tr
    %td
      住所
    %td
      = @group.setting.area
  %tr
    %td
      通知時刻
    %td
      = @group.setting.notice_at.strftime("%H:%M")
= link_to '登録内容を変更する', edit_group_path(@group)