config/routes.rb
LunchMail::Application.routes.draw do
  resources :groups do
    get :notice_all
    resources :users do
      member do
        get :notice
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :kicks, :only => %w() do
    member do
      get 'execute'
    end
  end

  root :to => "groups#show"

end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  belongs_to :group

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :active

  validates_presence_of :name

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.find_by_email(data.email)
      user
    else
      User.create!(:email => data.email, :password => Devise.friendly_token[0,20], :encrypted_password => Devise.friendly_token[0,20] )
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# -*- coding: utf-8 -*-
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = "ログインに成功しました。"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController

  def index
    @users = @group.users
  end

  def new
    @user = @group.users.build
  end

  def edit
    @user = @group.users.find(params[:id])
  end

  def create
    @user = @group.users.build(params[:user])
    @user.password = ActiveSupport::SecureRandom.base64(8)
    @user.active = true
    if @user.save
      redirect_to group_users_path(@group), :notice => "登録が完了しました。"
    else
      render :action => "new"
    end
  end

  def update
    @user = @group.users.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to group_users_path(@group), :notice => "登録情報を更新しました。"
    else
      render :action => "edit"
    end
  end

  def destroy
    @user = @group.users.find(params[:id])
    @user.destroy
    redirect_to group_users_path(@group), :notice => "登録を解除しました。"
  end

  def notice
    @user = @group.users.find(params[:id])
    @user.active = params[:status]
    @user.save
    respond_to do |format|
      format.js { render "notice"}
    end
  end
end

app/helpers/users_helper.rb
# -*- coding: utf-8 -*-
module UsersHelper
  def notice_td_content(user)
    content_tag(:div, :id => "notice-user-#{user.id}") do
      if user.active == true
        link_to "通知中", notice_group_user_path(@group, user, :status => "false"), :remote => true, :class => "btn mini primary"
      else
        link_to "通知する", notice_group_user_path(@group, user, :status => "true"), :remote => true, :class => "btn mini"
      end
    end
  end

  def notice_th_content
    content_tag(:div, :id => "notice-all-user") do
      if @group.users.select{ |user| user.active == false }.any?
        link_to "通知する", group_notice_all_path(@group, :status => "true"), :remote => true, :class => "btn mini"
      else
        link_to "通知中", group_notice_all_path(@group, :status => "false"), :remote => true, :class => "btn mini primary"
      end
    end
  end
end

app/views/users/_form.html.haml
= form_for [@group, @user] do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this setting from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .clearfix
    = f.label :name, "名前"
    .input
      = f.text_field :name
  .clearfix
    = f.label :email, "通知先メールアドレス"
    .input
      = f.email_field :email
  .actions
    = f.submit "メンバー登録", :class => "btn primary"

app/views/users/edit.html.haml
.page-header
  %h1 登録内容の変更

%p= link_to "<< メンバー一覧へ戻る", group_users_path(@group)

= render :partial => "form"

app/views/users/index.html.haml
.page-header
  %h1 ランチメンバー

%table.bordered-table.zebra-striped
  %tr
    %th.notice-btn
      = notice_th_content
    %th No.
    %th 名前
    %th 通知先メールアドレス
    %th

  - @users.each_with_index do |user,i|
    %tr
      %td.notice-btn
        = notice_td_content(user)
      %td
        = i + 1
      %td
        = user.name
      %td
        = user.email
      %td
        - if user != current_user
          = link_to "登録内容を変更する", edit_group_user_path(@group, user)
          |
          = link_to "登録を解除する", group_user_path(@group, user), :confirm => '登録を解除します。よろしいですか？', :method => :delete
= link_to "メンバーの登録", new_group_user_path

app/views/users/new.html.haml
.page-header
  %h1 メンバーの登録

%p= link_to "<< メンバー一覧へ戻る", group_users_path(@group)

= render :partial => "form"